### ISSUE TITLE
Testcase: Deploy the app

### ISSUE THREAD

**Issue by extsoft** [extsoft/dp-151#23]
Commit  the following `docker-compose.yaml` to the repo:
```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1.38-debian-9-r33'
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
  opencart:
    image: 'bitnami/opencart:3.0.3-1-debian-9-r55'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=${APP_HOST}
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
```

Testcase steps:
1. Connect to a server and create `oct` directory. 
2. Copy `docker-compose.yaml` to `oct` (is located within the repo)
3. Go to `oct` directory
4. Run `APP_HOST=localhost docker-compose up -d` on the server. You need to replace a `localhost` with a server IP
5. Run `docker-compose ps -q`. The output has to contain two non-empty lines like 
```
$ docker-compose ps -q
7c5985490a377c7813fb24bdb02f9f2f231d182b5d4e88c5572b1e52c5178a10
ae2492787d5b68b53b7c45e5c234c0b987e476bd2b7b1eeba27e1409512bb693
```

Server (works only under VPN):
192.168.195.143
user: adminaccount
pass: password

Implementation requirements:
1. a server has to be described in a testbed file
2. a server (device) name - `app` 
3. a server has to be injected as a device object (`from pyats.topology.device import Device`) into tests

Also, README has to be updated with instructions on how to deploy an app from a `docker-compose.yaml` on the local environment.

P.S. If you need to destroy app, run `docker-compose down`.
